### ISSUE TITLE
Composer with installation error

### ISSUE THREAD

**Issue by vladimirDaron** [sonatra/SonatraSecurityBundle#4]
Problem 1
    - Installation request for sonatra/security-bundle ~1.0@dev -> satisfiable by sonatra/security-bundle[1.0.x-dev].
    - sonatra/security-bundle 1.0.x-dev requires sonatra/cache ~1.0@dev -> no matching package found.

**Comment by francoispluchino** [comment]
Because you must add:
```json
{
    "sonatra/cache": "~1.0@dev"
}
```
