### ISSUE TITLE
OID collision

### ISSUE THREAD

**Issue by pawelsmolenski** [sonatra/SonatraSecurityBundle#5]
I think there is a possibility of collision of OIDs used in the Sonatra UOW.

I am creating a set of entities in batches. After flushing each batch I am unsetting its entities and clearing Doctrine Manager. This operation releases hashes previously generated by spl_object_hash function and makes them usable for other objects. As this operation is not detaching entries from Sonatra UOW originalObjectData array, random collisions ocure.

Regards.

**Comment by francoispluchino** [comment]
I use this bundle prod and I have never encountered this problem, but it is true that I do not perform your test in the same request.

I'm interested by your fix.

**Comment by pawelsmolenski** [comment]
I resolved this temporarily by disabling acl manager during batch import, but adding a listener to DoctrineManager clear and remove methods would be probably better solution. I will try to propose something, but now I am at the very begging of exploring your great bundle.
