### ISSUE TITLE
HelloGuest bundle

### ISSUE THREAD

**Issue by Eragon666** [sonatra/SonatraSecurityBundle#7]
Hi,

Still trying to install the bundle :)

I am getting the following error:
Fatal error: Class 'Helloguest\Bundle\CoreBundle\Security\Acl\Permission\PermissionMap' not found in /home/ubuntu/workspace/vendor/sonatra/security-bundle/Doctrine/ORM/Filter/AclFilter.php on line 41

I tried to search for this bundle, but couldn't find it. I also tried to find a way to set another class in the config, but couldnt find the correct way to do it.

**Comment by francoispluchino** [comment]
Oulala... I went a little fast. I will quickly fix this terrible error.

**Comment by francoispluchino** [comment]
Fixed by 645fb9c5f1e55a888da9c930602bca09124749ed.

**Comment by Eragon666** [comment]
Haha no problem. I will continue after you fixed it. 

Maybe its a good idea to make an (alpha) release after I installed it succesfully? So other users can use a 'stable' non-dev branch?

**Comment by francoispluchino** [comment]
It's expected, but not right away. I want to move all my tests (in this famous bundle :-)) and add others, before releasing the first Beta.

**Comment by Eragon666** [comment]
The fix seems to work, at least I am now locked out because I dont have the ACL permissions ;) 

Any estimates for the release? 

Also, do you think that we can already use this bundle for production (application is in development, so it will take a few weeks to months before deployment)?
Because it looks like this is exactly what we need :) 

Thanks for your great work!

**Comment by francoispluchino** [comment]
I use every Bundles of Sonatra in several small projects in production, and in a large project in development (Helloguest). I thought put all the libraries into stable version as soon as this big project will be deployed in production, ie, beginning in 2017 (Q1).

Regarding this bundle, I really need to add unit tests in the libraries before releasing a stable version. I hate release a stable version but buggy, or potentially buggy! But hey, this is for everyone! ;-)

If you're interested, you can look into my other organizations ([Fxp](https://github.com/fxpio), [Sonatra](https://github.com/sonatra)), that this bundle is part of the few Bundles without testing, and it's just intolerable to my mind. And yes I know ...

**Comment by francoispluchino** [comment]
I forgot to say, waiting for a stable version, that you can fix a particular commit of a branch in Composer:

```json
{
    "require": {
	    "friendsofsymfony/user-bundle": "^2.0.0@dev",
        "sonatra/security-bundle": "1.0.x-dev#645fb9c5f1e55a888da9c930602bca09124749ed"
    }
}
```

This way you do not risk having a compatibility break by an update dependencies.
