### ISSUE TITLE
Better requirements/ docs 

### ISSUE THREAD

**Issue by Eragon666** [sonatra/SonatraSecurityBundle#8]
I found some possible improvements for your composer requirements, or for in the docs. 

To be honest, I am not sure what exactly the JMS bundle is, and for what it is used in this bundle. But to get everything working, I needed to install and enable it in the AppKernel. So maybe add that to the documentation?

Also I had to install your DoctrineExtensionBundle (otherwise a error is thrown in sonatra/security-bundle/Core/Role/RoleHierarchy.php:163). 

I still have to complete some more steps before everything is working, so I might find more :)

**Comment by francoispluchino** [comment]
Thank you for returns. Indeed, there is a difference between the doc and code... Always due to missing tests.

Normally, JMS is optional and DoctrineExtensionBundle should not be required. Only FOS UserBundle is required. I think I'll extract the utility classes in a library. I will fix it quicly.

**Comment by Eragon666** [comment]
If I have time I will setup a seperate devbox for this bundle, so I will be able to push changes If I find an error. But at this moment I dont have time to do it :)

Also, I have an error with my debugbar Security overview. When I open the security overview, I get the following error:

CRITICAL - Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Notice: Undefined index: voters") in "@Security/Collector/security.html.twig" at line 123." at /home/ubuntu/workspace/app/cache/dev/classes.php line 5384 

So it looks like something is wrong with the voters, but I thought these wouldnt be necessary when using ACL? Or am I wrong? 

For the time being I disabled the rows in Symfiny source code, but that is a far from ideal situation ofcourse. 

Do you know if this is an error in this bundle or in Symfony? Or did I forget something?

**Comment by francoispluchino** [comment]
I have:
- remove the dependency of Sonatra DoctrineExtensionsBundle (7b3fb09246d86075fdec4298f98b7ef6b04cac50)
- update the default config to disable JMS Expressions and add some validations (ccada45b942b47df32e6020446f7a51503ae4943)
- update the doc (1009793b0fd9d9146be7bc3e0604e280ee17e12f)

**Comment by francoispluchino** [comment]
I use the Symfony 3.1.5 with this Bundle, and I haven't your problem. After regarding the template [@Security/Collector/security.html.twig](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/SecurityBundle/Resources/views/Collector/security.html.twig#L123), I see that the variable `voters` is not present in the variable` collector`, and this bundle does not change the debug collector.

The strange thing is that there is a replacement value if the `voters` variable does not exist.

**Comment by francoispluchino** [comment]
Is it Ok for you?

**Comment by Eragon666** [comment]
Hi, Sorry I wasn't able to work on the project today. Thanks for the fixes, I will update the bundle as soon as I am home again. 

I also looked in the security.html.twig file, and it is indeed really strange that it throws an error. Maybe there is something from on my end in the project. For now I just disabled it in the plugin, but that will throw errors when I update it. So I will have to find a permanent fix :)

**Comment by Eragon666** [comment]
Good news, updating to the latest version fixed the problem with Twig/debugbar!

**Comment by francoispluchino** [comment]
Cool! This issue can be closed?

**Comment by Eragon666** [comment]
Yes! I will open another issue if I find another problem/question!
